"""add_likes

Revision ID: 079dc68162f7
Revises: 61b84bc96a79
Create Date: 2025-04-03 18:25:32.894682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079dc68162f7'
down_revision: Union[str, None] = '61b84bc96a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_liked_memes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('meme_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ),
    sa.ForeignKeyConstraint(['user_telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('memes', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('likes', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_table('user_liked_memes')
    # ### end Alembic commands ###
