"""meme_collections_relationship

Revision ID: af687836febc
Revises: 8c1d42e2a5d2
Create Date: 2025-04-07 14:33:09.586605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af687836febc'
down_revision: Union[str, None] = '8c1d42e2a5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_to_collection',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meme_id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('collections', 'meme_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('meme_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False))
    op.drop_table('meme_to_collection')
    # ### end Alembic commands ###
