services:
  database:
    image: groonga/pgroonga
    ports:
      - "5432:5432"
    env_file: ".env"
    command: ["postgres", "-c", "enable_seqscan=off"]
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  bot:
    build: ./bot_backend/
    env_file: ".env"
    image: bot_image
    restart: always
    depends_on:
      - database
volumes:
  postgres-data:
    driver: local