services:
  database:
    image: groonga/pgroonga
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "enable_seqscan=off"]
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Memes
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
volumes:
  postgres-data-test:
    driver: local