name: Deploy to DigitalOcean
on:
  push:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2
  
        - name: Set up Python
          uses: actions/setup-python@v5.5.0
          with:
            python-version: '3.11'
            
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run migrations
          run: alembic upgrade head > /dev/null 2>&1
          env:
            ALEMBIC_DATABASE_URL: ${{ secrets.ALEMBIC_DATABASE_URL }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
    - name: Clone repo to droplet
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd /home
            # git clone or pull repo
            if cd MemeSender; then git pull; else git clone git@github.com:pixol20/MemeSender.git && cd MemeSender; fi

            echo "${{ secrets.DOTENV }}" > ./.env
            
            # build and run compose project
            docker compose up -d --build
      
      
